### ISSUE TITLE
Console warnings with CM6 - deprecated packages

### ISSUE THREAD

**Issue by danieltomasz** [mgmeyers/obsidian-pandoc-reference-list#39]
When installed 0.15.1
```
app.js:1 Error: [CM6][obsidian-pandoc-reference-list] Using a deprecated package: "@codemirror/rangeset".
See the stack trace to find the faulty plugin and file an issue with the plugin author. 
Details: https://discuss.codemirror.net/t/release-0-20-0/4302
    at o (app.js:1:1536192)
    at anonymous (plugin:obsidian-pandoc-reference-list:2948:34)
    at e.<anonymous> (app.js:1:1536487)
    at app.js:1:234938
    at Object.next (app.js:1:235043)
    at s (app.js:1:233782)
```
another  errors
```
Error: [CM6][obsidian-pandoc-reference-list] Using a deprecated package: "@codemirror/stream-parser".
See the stack trace to find the faulty plugin and file an issue with the plugin author. 
Details: https://discuss.codemirror.net/t/release-0-20-0/4302
    at o (app.js:1:1536192)
    at anonymous (plugin:obsidian-pandoc-reference-list:2950:39)
    at e.<anonymous> (app.js:1:1536487)
    at app.js:1:234938
    at Object.next (app.js:1:235043)
    at s (app.js:1:233782)
```

Plugin is working.

**Comment by mgmeyers** [comment]
This should be fixed in the latest version @danieltomasz
